logging:
  level:
    tacos: DEBUG #tacos 包

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/taco?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: fengsc2017


